app:
  version: '@project.version@'
fiware:
  context-broker-url: ${CONTEXT_BROKER_URL}
logging:
  level:
    root: info
    de.app.fivegla: trace
    one.microstream: debug
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2