### Get version
GET {{base-url}}/info/version

### Process image
POST {{base-url}}/images/
Content-Type: application/json

{
  "droneId": "14111983",
  "micaSenseChannel": "RED",
  "base64Image": "{{base64-encoded-tiff-image}}"
}

### Get image
GET {{base-url}}/images/aace4b53-6265-4279-b588-61c2d98d24a7
