### Get version
GET {{base-url}}/info/version

### Register drone
POST {{base-url}}/drone/register
Content-Type: application/json

{
  "droneId": "14111983"
}

### Process immage
POST {{base-url}}/images/
Content-Type: application/json

{
  "droneId": "14111983",
  "micaSenseChannel": "RED",
  "base64Image": "{{base64-encoded-tiff-image}}"
}

### Get image
GET {{base-url}}/images/{{image-oid}}
