### Get version
GET {{base-url}}/info/version

### Process immage
POST {{base-url}}/image-processing/
Content-Type: application/json

{
  "micaSenseChannel": "RED",
  "base64EncodedTiffImage": "{{base64-encoded-tiff-image}}"
}
