name: CI

on:
  pull_request:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build_jdk_17:
    name: Build with Java 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify --file pom.xml --settings .github/settings.xml